version: "3"
services:
  app:
    # replace username/repo:tag with your name and image details
    image: tomcat:8.0-jre8
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    ports:
      - 8888:8080
    volumes:
      # - tomcat:/usr/local/tomcat
      - .:/usr/local/tomcat/webapps/app
      # - /Users/yuhei.shimizu/development/docker/tomcat:/usr/local/tomcat
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
volumes:
  tomcat:
    driver: local
    # networks:
    #   - webnet
#   visualizer:
#     image: dockersamples/visualizer:stable
#     ports:
#       - "8080:8080"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock"
#     deploy:
#       placement:
#         constraints: [node.role == manager]
#     networks:
#       - webnet
#   redis:
#     image: redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - /home/docker/data:/data
#     deploy:
#       placement:
#         constraints: [node.role == manager]
#     command: redis-server --appendonly yes
#     networks:
#       - webnet
# networks:
#   webnet:
